### PR TITLE
Drop OS/ARCHITECTURE macros to make build reproducible

### PR DESCRIPTION
**Pull request by basilgello**

### CODE REVIEW

**Comment by basilgello** [comment]
@gade01 :)

**Review by AlwinEsch — APPROVED** [review]
From my side OK and good to have them removed.

To use this has never made sense for me, as a e.g. Linux compiled addon can never be shown or installed on Kodi by e.g. Windows OS.

**Comment by AlwinEsch** [comment]
Maybe in this case makes a additional commit to increase version to 20.1.1 and new release about.

**Review by gade01 — APPROVED** [review]
@basilgello Looks very good to me.

**Review by phunkyfish — APPROVED** [review]

**Pull request merged**
