### PR TITLE
Drop OS/ARCHITECTURE macros to make build reproducible

### PR DESCRIPTION
**Pull request by basilgello**

### CODE REVIEW

**Comment by basilgello** [comment]
@gade01 :)

**Review by AlwinEsch — APPROVED** [review]

**Comment by AlwinEsch** [comment]
Maybe in this case makes a additional commit to increase version to 19.0.1 and new release about.

**Review by gade01 — APPROVED** [review]
@basilgello Looks very good to me.
Please merge https://github.com/kodi-pvr/pvr.wmc/pull/110 first.

**Comment by basilgello** [comment]
@phunkyfish @AlwinEsch can you please merge it?

**Review by phunkyfish — APPROVED** [review]

**Pull request merged**
