### PR TITLE
[pvr] Add support for Kodi 16 API 3.0 Series Timers

### PR DESCRIPTION
**Pull request by ryangribble**
This is the pvr.wmc implementation for Kodi16/API 3.0 Series Timer changes in https://github.com/xbmc/xbmc/pull/7079 and https://github.com/xbmc/xbmc/pull/7626

- Removed old custom series recording implementation and custom confluence dialogs
- Implemented new Kodi TimerTypes for Manual, Guide and Wishlist (keyword search) type recordings, both One-Shot and Repeating
- Kodi fields used: Lifetime, Priority, PreventDuplicates, MaxRecordings, Pre/Post Padding, Start AnyTime, DayOfWeek, Keyword Search

@metaron-uk @ksooo @janbar @krustyreturns  @xhaggi @hudokkow @Jalle19

### CODE REVIEW

**Comment by hudokkow** [comment]
Forst or not, code indent is all over the place. Using <code>?w=1</code> doesn't make it any easier...
Can't you educate your IDE?

**Comment by ryangribble** [comment]
If you add ?ts=4 to the URL it should line up.  Normally i wouldnt even use tabs as I prefer spaces but I am trying to match the existing whitespace formatting of these files as I dont want to "change" every single line by converting whitespace.

github seems to be showing tabs as 8 spaces which seems unusual... the default setting in Visual Studio is 4, so adding ?ts=4 will make github line things up

**Comment by ryangribble** [comment]
If there is no other comments/feedback am I right to merge this? Is there a way to trigger a test build of an addon PR or do we have to merge and then see what happens?! 

@ksooo @metaron-uk

**Comment by hudokkow** [comment]
Merge and see what happens. Keep an eye on jenkins builds.

**Comment by metaron-uk** [comment]
@ryangribble I'm not ignoring you, I just don't see I can bring anything to the party. Your description of the change looks sensible to me. Unfortunately I don't have wmc myself so can't test it. Publish and be dammed!

**Comment by ryangribble** [comment]
all good.  I was waiting while we got a beta release of ServerWMC together so any users that want to test the nightly builds have a backend with the required changes.  Hitting the button now!

**Pull request merged**
