### PR TITLE
Update to API 4.2.0 - Implement IsRealTimeStream()

### PR DESCRIPTION
**Pull request by hudokkow**
Will merge tonight if nobody objects.

### CODE REVIEW

**Comment by ryangribble** [comment]
Hi, could you please bump version number in clientversion.h file as well?

Thanks!

**Comment by hudokkow** [comment]
Done!

**Comment by ryangribble** [comment]
Thanks! 

Ideally we would generate the header file during build, from the addon.xml but not sure how to do that with cmake!

**Comment by hudokkow** [comment]
7 *Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you.* 8 *For everyone who asks receives, and he who seeks finds, and to him who knocks it will be opened.*

Matthew 7:7

--- > https://github.com/kodi-pvr/pvr.mediaportal.tvserver/commit/8d0b7a40112f149ddc465aa86d0e0db988475dab

**Comment by hudokkow** [comment]
Closing this. See https://github.com/kodi-pvr/pvr.dvblink/pull/39

**Pull request closed without merging**
