### PR TITLE
Fix conflict with pvr-hts

### PR DESCRIPTION
**Pull request by diogomsantos**

### CODE REVIEW

**Comment by diogomsantos** [comment]
Can you please fix this ? Like it is, makes the installation of all debian pvr packages impossible, you can only enable one pvr at a time in Kodi, so the the conflict/replace, makes no sense.

**Comment by Jalle19** [comment]
Major WTF. @wsnipex is there any reason for this or is it a copy-paste error from back in the day?

**Comment by wsnipex** [comment]
-1 on merging this. The conflict is there for a reason: there was an old and incompatible kodi-pvr-tvheadend-hts package. The new one is kodi-pvr-hts

**Comment by Jalle19** [comment]
@wsnipex still it would only make sense for pvr.hts to have `Conflicts` here, not all PVR addons?

**Comment by wsnipex** [comment]
uh, didn't really notice this is not against pvr.hts.
So yes, this must be some copy/paste error and should go

**Pull request merged**
